### ISSUE TITLE
require.context replacement doesn't work for nested paths on Windows

### ISSUE THREAD

**Issue by danielelkington** [IndexXuan/vue-cli-plugin-vite#13]
This plugin will rewrite the following
```js
const customTabsContext = require.context('@/components/tabs', true, /^.*(.vue)$/)
```
to something like this when using Windows:
```js
const customTabsContext = 
  (function() {
    var map = {
      './category1\Tab1.vue': import_context_module_0_0,
'./category1\Tab2.vue': import_context_module_0_1,
'./category2\Tab3.vue': import_context_module_0_2,

    };
    var req = function req(key) {
      return map[key] || (function() { throw new Error("Cannot find module '" + key + "'.") }());
    }
    req.keys = function() {
      return Object.keys(map);
    }
    return req;
  })()
```
Note that the keys in the map use backslashes `\` for nested paths. However to put a backslash into a string literal you need to escape it `\\`. Therefore `require.context` won't work for nested paths on Windows.

This works fine on Mac OS, as the keys in the map will use forward slashes `/`.

**Comment by IndexXuan** [comment]
@danielelkington dont't have Windows PC, would you mind give a PR ?
I think https://vitejs.dev/guide/api-plugin.html#path-normalization maybe help.

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/lib/resolve.ts#L99
https://nodejs.org/api/path.html#path_path_relative_from_to
L99 wrapped in vite#normalizePath will help ? can you do it locally(./node_modules/vite-plugin-vue-cli/dist/index.js) and give a feedback ?

**Comment by danielelkington** [comment]
Will give this a go tomorrow. Thanks for creating this awesome plug-in!

**Comment by danielelkington** [comment]
You're right - `normalizePath` fixed the problem. Have raised a PR.

**Comment by IndexXuan** [comment]
Release: v0.3.2

BTW I change [src/lib/resolve.ts#L100](https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/lib/resolve.ts#L100) to pass my [testcase](https://github.com/IndexXuan/vue-enterprise-boilerplate/commits/feature/vite), if something wrong, please feedback.
