### ISSUE TITLE
Could not resolve "@/App.vue"

### ISSUE THREAD

**Issue by miguelrk** [IndexXuan/vue-cli-plugin-vite#14]
Hello everyone! Thanks for this great plugin.

Beginner question here: I tried setting it up but get `Could not resolve "@/App.vue" (mark it as external to exclude it from the bundle)` when running. According to the readme, `@` should be auto-resolved. Am I missing something? 

I tried adding 

```javascript
// vue.config.js
{
  // ...
  pluginOptions: {
    vite: {
       alias: {
         '@': path.resolve(__dirname, './src'), // this
         '@/': path.resolve(__dirname, './src/'), // and also this
       },
  },
}
```

but none worked. Any help would be greatly appreciated! I'm using a Vue 2 app built with Vue CLI (+ Vuetify)

**Comment by IndexXuan** [comment]
@miguelrk 
Hi there. First of all, make sure to use latest version v0.3.2. ( pluginOptions.vite.alias is no need since v0.2.2. )
you can add console.log in `L66` of your local `./node_modules/vue-cli-plugin-vite/config/index.ts` file, see what alias finally output.
without a reproduction repo, it is hard to share some help for you.

**Comment by miguelrk** [comment]
Hey @IndexXuan ! Thanks for the quick response! The aliases are indeed resolved correctly The problem was I should have been running `npm run vite` instead of simply `vite`. That did it. Maybe add `npm run vite` after the `vue add vite` line in the usage section of the README?

Now I'm having issues with my component imports not having `.vue` at the end, but I'll convert them manually (as the README says) and let you know if I get this to work.

**Comment by IndexXuan** [comment]
@miguelrk Thanks for feedback, yes, `yarn vite` and `vite` will confuse the beginners, I will doc it.
