### ISSUE TITLE
Question: How to use different code for Vite and Vue cli

### ISSUE THREAD

**Issue by Djaler** [IndexXuan/vue-cli-plugin-vite#16]
For example, I have to inject some variables during build, so in client code I need to write process.env.VUE_APP_XXX or import.meta.env.VITE_XXX. Is there a way to use one code when building using Vue cli and another when using Vite?

**Comment by IndexXuan** [comment]
vite only load env from .env.* files, and vue-cli load from .env.* files and Node Process. So you can use something like
`VUE_APP_VUE_CLI=on yarn dev` for vue-cli and `yarn vite` for vite. and `VUE_APP_VUE_CLI=on yarn build` for vue-cli and `yarn build:vite` for vite.

```json
"scripts": {
     "vite": "node ./bin/vite",
    "build:vite": "BUILD=on MODERN=on yarn vite",
    "dev": "VUE_APP_VUE_CLI=on vue-cli-service serve",
    "build": "VUE_APP_VUE_CLI=on vue-cli-service build"
}
```

testcase: you can put these code in src/main.js
```js
if (process.env.VUE_APP_VUE_CLI === 'on') {
  console.log('I am in vue-cli')
} else {
  console.log('I am in vite')
}
```

pay attention:
1. never use import.meta.env before you natively migration to vite
2. VUE_APP_VUE_CLI must in npm scripts or in cmd, cannot in .env.*
3. must include `VUE_APP_` prefix for client-code

**Comment by IndexXuan** [comment]
@Djaler 
No need to do above !!!
As of latest `v0.3.3`. you can directly use `process.env.VITE === true` to check you use vite or vue-cli.
you can try it.

**Comment by Djaler** [comment]
So, there are no way to inject env variables when run using vite?
I thought that maybe this can work:
```
let someUrl;
if (process.env.VITE === true) {
  someUrl = import.meta.env.VITE_SOME_URL
} else {
  someUrl = process.env.VUE_APP_SOME_URL
}
```

**Comment by IndexXuan** [comment]
@Djaler 
you did not read what I said ?

```js
let someUrl;
if (process.env.VITE === true) {
  someUrl = 'host1' // or process.env.VUE_APP_API_FOR_VITE, list in .env.* files
} else {
  someUrl = 'host2' // or process.env.VUE_APP_API_FOR_VUE_CLI, list in .env.* files
}
```

never use `import.meta.env`

**Comment by Djaler** [comment]
Ok, that't sad

**Comment by IndexXuan** [comment]
@Djaler sad for what ? It works.

**Comment by Djaler** [comment]
Ok, sorry. I just thought that I can't use env in vite using process.env completely. Now I see that it works, thanks

**Comment by Djaler** [comment]
Wow, looks like even `require.context` works. But how? I thought that this is webpack-only feauture and one should use `import.meta.glob` in vite instead

**Comment by IndexXuan** [comment]
@Djaler you should read about README ~ this plugin do something underlying and help you lint your codebase for migration to vite completely in the future. Enjoy it.
