### ISSUE TITLE
Crashes on init

### ISSUE THREAD

**Issue by probil** [IndexXuan/vue-cli-plugin-vite#20]
```
✔  Successfully installed plugin: vue-cli-plugin-vite

? Please select the HTML init method default (Create a new HTML in the root directory)
ERROR  RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2613585960) is greater than possible Buffer: 2147483647 bytes
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2613585960) is greater than possible Buffer: 2147483647 bytes
    at tryCreateBuffer (fs.js:335:13)
    at Object.readFileSync (fs.js:371:14)
    at readFiles (/Users/max/.volta/tools/image/packages/@vue/cli/lib/node_modules/@vue/cli/lib/util/readFiles.js:21:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by probil** [comment]
I had several large files in the `tmp` directory. Fixed by ignoring them:
`@vue/cli/lib/node_modules/@vue/cli/lib/util/readFiles.js:L13`:
```diff
- ignore: ['**/node_modules/**', '**/.git/**'],
+ ignore: ['**/node_modules/**', '**/.git/**', '**/tmp/**'],

**Comment by xmasong** [comment]
@probil  When Vue-CLI invoke the plugin, it reads all the files in the current directory (ignore only a few directories as shown). And 2147483647 bytes is the maximum size a Buffer can have in NodeJS.  So you need to make sure that no files in your current directory exceed this limit.
![image](https://user-images.githubusercontent.com/22997127/113145277-d6037a80-9260-11eb-971a-ab73fcc3c3d8.png)
