### ISSUE TITLE
html plugins title undefined

### ISSUE THREAD

**Issue by lanseria** [IndexXuan/vue-cli-plugin-vite#24]
```
config.plugin("html").tap(args => {
      console.log(args);
      args[0].title = "";
      return args;
})
```

```
$ node ./bin/vite
running: vite --config C:\code\iep-ui\node_modules\vue-cli-plugin-vite\config\index.ts
[]
error when starting dev server:
TypeError: Cannot set property 'title' of undefined
    at C:\code\iep-ui\vue.config.js:40:21
    at Object.tap (C:\code\iep-ui\node_modules\vite-plugin-vue-cli\dist\index.js:336:24)
    at Object.chainWebpack (C:\code\iep-ui\vue.config.js:38:27)
    at Object.config (C:\code\iep-ui\node_modules\vite-plugin-vue-cli\dist\index.js:10189:19)
    at C:\code\iep-ui\node_modules\vite\dist\node\chunks\dep-66eb515d.js:45908:27
    at Array.forEach (<anonymous>)
    at resolveConfig (C:\code\iep-ui\node_modules\vite\dist\node\chunks\dep-66eb515d.js:45906:17)       
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createServer (C:\code\iep-ui\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69132:20)  
    at async CAC.<anonymous> (C:\code\iep-ui\node_modules\vite\dist\node\cli.js:14037:24)
```

版本: 1.55.2 (user setup)
提交: 3c4e3df9e89829dce27b7b5c24508306b151f30d
日期: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by IndexXuan** [comment]
I have no iead of what you said

**Comment by IndexXuan** [comment]
plz give reproduce repo or link.

**Comment by IndexXuan** [comment]
modify title. you can use vue.config.js pages for MPA. for SPA just set in html template.
It works for both vue-cli and vite.

**Comment by IndexXuan** [comment]
also when use webpack chain to modify webpack config. It is reccommended to first check config.plugins.has html and then modify it.

**Comment by lanseria** [comment]
> modify title. you can use vue.config.js pages for MPA. for SPA just set in html template.
> It works for both vue-cli and vite.

https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin

I want to pass variables to the index.html file in the official documentation, which works in vue-cli, but using this vite plugin is problematic

**Comment by IndexXuan** [comment]
because this plugin try my best to help vue-cli using vite. But it is not perfact. You must use right way to help this plugin work and keep vue-cli work as well.

you can check examples for title modify.
https://github.com/IndexXuan/vue-enterprise-boilerplate/blob/feature/vite/vue.config.js#L9
