### ISSUE TITLE
Vue2-Compatibilty broke with 1.0.0-rc4

### ISSUE THREAD

**Issue by MinerMax555** [IndexXuan/vue-cli-plugin-vite#26]
Hey there,

your recent update which added Vue3 support broke compatibility with Vue2. It properly starts but I get an error because it can't import createVNode (which is a Vue3-exclusive function).

I tracked it back to this likely origin:
1.) Install vue-cli-plugin-vite into a vue2 project
2.) Run npm explain vue => Both vue2 (from project itself) and vue3 (vue-cli-plugin-vite => @vitejs/plugin-vue => vue3.x) are installed
3.) The code which calculates current vue version does a require('vue') but grabs Vue3 even though it is a Vue2 Project

A possible solution to fix this could be to declare both @vitejs/plugin-vue and vite-plugin-vue2 as [Peer Dependencies](https://nodejs.org/es/blog/npm/peer-dependencies/) and require the end user to manually install whichever they need. Then only the correct vue version would be present.

**Comment by IndexXuan** [comment]
thanks feedback. I will check it.

**Comment by IndexXuan** [comment]
I dont think plugin-vue should include Vue3.x it self, it should be peerDeps. maybe you use new version of npm.

https://stackoverflow.com/questions/66239691/what-does-npm-install-legacy-peer-deps-do-exactly-when-is-it-recommended-wh

**Comment by IndexXuan** [comment]
npm v7

https://stackoverflow.com/questions/66020820/npm-when-to-use-force-and-legacy-peer-deps?rq=1

**Comment by IndexXuan** [comment]
any feedback?

**Comment by MinerMax555** [comment]
Hi, sorry for taking this long to write back. Indeed using either the --legacy-peer-deps option or npm 6 solved the issue. Thanks for helping me!

**Comment by MinerMax555** [comment]
So i tried the following:
+ Completely delete node_modules
+ Delete package-lock.json
+ Use npm 6 to install

It doesn't install Vue3 anymore, but I get a vuetify issue that multiple instances of Vue are being detected and nothing will load because of that:

![image](https://user-images.githubusercontent.com/12732580/117114577-52233d80-ad8c-11eb-93e6-3e751c3ee450.png)

**Comment by IndexXuan** [comment]
I think it is runtime error, please google/stackoverflow it. or find sth in vite issues about vuetify.

**Comment by MinerMax555** [comment]
Indeed I already did some searching regarding this, but this issue doesnt appear when the only thing I change is the version of your plugin to 1.0.0-rc3. So either it has something to do with your plugin or with the changes of your dependencies since then. I'll start some further investigation when I have time.

**Comment by IndexXuan** [comment]
sorry for that. or you can give min repro repo I can help.

**Comment by MinerMax555** [comment]
@IndexXuan I finally managed to find out what is happening. Turns out some legacy thing in the codebase required that  `runtimeCompiler: true` be enabled in vue.config.js

That caused your code here (https://github.com/IndexXuan/vite-plugin-vue-cli/blob/d1f93dc5de97c9ffff0b0d685361285a9eded6dc/src/index.ts#L83) to import `vue/dist/vue.runtime.esm.js` while Vuetify still internally imported  `vue/dist/vue.esm.js`, duplicating Vue and breaking the application.

By updating that legacy piece and removing that line from the config I managed to get everything to work properly
