### ISSUE TITLE
When vue-router is set to history mode, 404 problems will appear

### ISSUE THREAD

**Issue by sh-winter** [IndexXuan/vue-cli-plugin-vite#28]
Example: [click here](https://github.com/sh-winter/viue-cli-plugin-vite-test)
Step: after the page is opened, click `about` and refresh the page

**Comment by IndexXuan** [comment]
known issue since we use html-template. maybe you can use hash first. I will release new version which is able to disabled html-template and use real html entry. wait me.

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-html-template/blob/main/src/index.ts#L33
help wanted.

**Comment by IndexXuan** [comment]
workaround: as of plugin@v1.1.0

1. disabled html-template
```js
// vue.config.js
{
  // others.
  pluginOptions: {
    // others
    vite: {
      // others
      disabledHtmlTemplate: true,
    }
  }
}
```

2. create index.html in projectRoot like @vitejs/create-app. the content is:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main"></script>
  </body>
</html>
```

**Comment by sh-winter** [comment]
I feel [this](https://github.com/vitejs/vite/issues/3354#issuecomment-842331283) may help you

**Comment by IndexXuan** [comment]
@sh-winter v1.1.0 works?

**Comment by sh-winter** [comment]
I haven't tried yet. I'm going to work 😜

**Comment by IndexXuan** [comment]
v1.1.1
