### ISSUE TITLE
Why always remind me: new dependencies found ?

### ISSUE THREAD

**Issue by sh-winter** [IndexXuan/vue-cli-plugin-vite#29]
I don't know why, but `vite` won't bring me such an experience. If `optimizeDeps.Include` can be optimized, can such code be used for preprocessing?

```javascript
const { name, dependencies } = require('./package.json')

module.exports = {
    pluginOptions: {
        vite: {
            optimizeDeps: {
                include: [
                    ...Object.keys(dependencies)
                ]
            }
	}
    }
}
```

**Comment by IndexXuan** [comment]
I think it should works. anything in optimizeDeps.include string[] should be prebundle and speedup devServer start time.

**Comment by IndexXuan** [comment]
as of v1.1.3 it is fixed. try it ?
