### ISSUE TITLE
vue-cli@4 vue2 project throw error

### ISSUE THREAD

**Issue by Yuliang-Lee** [IndexXuan/vue-cli-plugin-vite#30]
![image](https://user-images.githubusercontent.com/6936358/119259315-42b34980-bc00-11eb-8480-ab22509e2280.png)

@vitejs/plugin-vue already installed

**Comment by IndexXuan** [comment]
read FAQ fisrt. maybe you import vue without .vue ext? or sth. No enough information for me.

**Comment by Yuliang-Lee** [comment]
I found that when my .vue file has 
![image](https://user-images.githubusercontent.com/6936358/119260702-84df8980-bc06-11eb-894b-4af96f13543d.png)
code like these the problem happened

**Comment by IndexXuan** [comment]
always use jsx syntax in .jsx file.

**Comment by jingguangyan** [comment]
> always use jsx syntax in .jsx file.

[example](https://github.com/jingguangyan/jsx-issue-example)

I read "FAQ" and set `vitePluginVue2Options: {jsx: true }`.
I made sure to only use jsx syntax in .jsx files, but it doesn't work:
![error-image](https://user-images.githubusercontent.com/24221158/120617814-0cda5480-c48d-11eb-9001-1619cf8b69b6.jpg)

**Comment by IndexXuan** [comment]
got it, maybe a vite-plugin-vue2 jsx issue. I will debug your example first.

**Comment by IndexXuan** [comment]
https://github.com/vuejs/jsx/issues/34#issuecomment-479816621
use this config. I works for me.

**Comment by IndexXuan** [comment]
![image](https://user-images.githubusercontent.com/6322673/120643610-f6da8d00-c4a8-11eb-9337-1bbbcd2ff595.png)
all the diff with your example project.

**Comment by jingguangyan** [comment]
> [vuejs/jsx#34 (comment)](https://github.com/vuejs/jsx/issues/34#issuecomment-479816621)
> use this config. I works for me.

Thank you very much for your timely feedback, it can work normally.

**Comment by jingguangyan** [comment]
On this basis, I integrated composition-api and supported jsx syntax. 
Add `compositionAPI: true` to the babel.config.js file. 
Then there is no need to change `injectH` according to the environment.

Similarly, we should always use jsx syntax in `.jsx` files.


![20210604151322](https://user-images.githubusercontent.com/24221158/120761323-a8300000-c547-11eb-9029-ead1b75308b7.jpg)

![20210604151601](https://user-images.githubusercontent.com/24221158/120761484-d1509080-c547-11eb-8ecb-563121076713.jpg)
