### ISSUE TITLE
got error when running script "npm run vite"

### ISSUE THREAD

**Issue by xxrt** [IndexXuan/vue-cli-plugin-vite#32]
vue version: @vue/cli 4.5.13
node version: v14.16.1
npm version: 6.14.12

[~/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring]$ npm run vite

> spot-exploring@2.4.0 vite /Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring
> node ./bin/vite

running: vite --config /Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vue-cli-plugin-vite/config/index.ts
error when starting dev server:
TypeError: Cannot read property 'compilerOptions' of undefined
    at /Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/vue.config.js:81:17
    at Object.tap (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vite-plugin-vue-cli/dist/index.js:593:20)
    at Object.chainWebpack (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/vue.config.js:80:8)
    at Object.config (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vite-plugin-vue-cli/dist/index.js:10189:19)
    at resolveConfig (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:70419:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createServer (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:68943:20)
    at async CAC.<anonymous> (/Users/chent/Documents/zykj/maintanence/03Develop/trunk/client/spot-exploring/node_modules/vite/dist/node/cli.js:13892:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spot-exploring@2.4.0 vite: `node ./bin/vite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spot-exploring@2.4.0 vite script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chent/.npm/_logs/2021-06-09T01_20_24_962Z-debug.log

**Comment by xxrt** [comment]
vue-cli version: @vue/cli 4.5.13

**Comment by IndexXuan** [comment]
sorry I can do nothing with your information. At least you should give your vue.config.js and a mini repro demo will be better.

**Comment by xxrt** [comment]
it is our vue.config.js below

`'use strict'
const path = require('path')
const defaultSettings = require('./src/settings.js')

function resolve(dir) {
  return path.join(__dirname, dir)
}

const name = defaultSettings.title 
const port = 8013 // 端口配置

// All configuration item explanations can be find in https://cli.vuejs.org/config/
module.exports = {
  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: false,
  productionSourceMap: false,
  devServer: {
    port: port,
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },
    proxy: {
      '/api': {
        target: process.env.VUE_APP_BASE_API,
        changeOrigin: true,
        pathRewrite: {
          '^/api': 'api'
        }
      },
      '/auth': {
        target: process.env.VUE_APP_BASE_API,
        changeOrigin: true,
        pathRewrite: {
          '^/auth': 'auth'
        }
      }
    }
  },
  configureWebpack: {
    // provide the app's title in webpack's name field, so that
    // it can be accessed in index.html to inject the correct title.
    name: name,
    resolve: {
      alias: {
        '@': resolve('src'),
        '@crud': resolve('src/components/Crud')
      }
    }
  },
  chainWebpack(config) {
    config.plugins.delete('preload') // TODO: need test
    config.plugins.delete('prefetch') // TODO: need test

    // set svg-sprite-loader
    config.module
      .rule('svg')
      .exclude.add(resolve('src/assets/icons'))
      .end()
    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(resolve('src/assets/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
      .end()

    // set preserveWhitespace
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(options => {
        options.compilerOptions.preserveWhitespace = true
        return options
      })
      .end()

    config
      // https://webpack.js.org/configuration/devtool/#development
      .when(process.env.NODE_ENV === 'development',
        config => config.devtool('cheap-source-map')
      )

    config
      .when(process.env.NODE_ENV !== 'development',
        config => {
          config
            .plugin('ScriptExtHtmlWebpackPlugin')
            .after('html')
            .use('script-ext-html-webpack-plugin', [{
            // `runtime` must same as runtimeChunk name. default is `runtime`
              inline: /runtime\..*\.js$/
            }])
            .end()
          config
            .optimization.splitChunks({
              chunks: 'all',
              cacheGroups: {
                libs: {
                  name: 'chunk-libs',
                  test: /[\\/]node_modules[\\/]/,
                  priority: 10,
                  chunks: 'initial' // only package third parties that are initially dependent
                },
                elementUI: {
                  name: 'chunk-elementUI', // split elementUI into a single package
                  priority: 20, // the weight needs to be larger than libs and app or it will be packaged into libs or app
                  test: /[\\/]node_modules[\\/]_?element-ui(.*)/ // in order to adapt to cnpm
                },
                commons: {
                  name: 'chunk-commons',
                  test: resolve('src/components'), // can customize your rules
                  minChunks: 3, //  minimum common number
                  priority: 5,
                  reuseExistingChunk: true
                }
              }
            })
          config.optimization.runtimeChunk('single')
        }
      )
  }
}
`

**Comment by xxrt** [comment]
TypeError: Cannot read property 'compilerOptions' of undefined

有这个错误信息，compilerOptions好像是typescript的选项？您这个工具有要求一定要用typescript吗？我这个工程没有用typescript

**Comment by IndexXuan** [comment]
```js
// set preserveWhitespace
config.module
  .rule('vue')
  .use('vue-loader')
  .loader('vue-loader')
  .tap(options => {
    options.compilerOptions.preserveWhitespace = true
    return options
  })
  .end()
```
`this compilerOptions`

you know that vite does not have webpack loaders & plugins. so you should write **universal vue.config.js config**

It means
```js
// check exists before do something
if (config.plugins.has('xxx') {
  // then do sth with this webpack plugin(like tap it)
}

// check options exists before mutable it.
.tap(options => {
 ++   if (options) {
    options.compilerOptions.preserveWhitespace = true
   return options
 ++   }
  })

**Comment by IndexXuan** [comment]
vue-cli-plugin-vite will read you vue.config.js, get some config for vite config, so it is important to write **universal vue.config.js** in chainWebpack

**Comment by IndexXuan** [comment]
any feedback?
