### ISSUE TITLE
CDN引入的vue报错Error: Cannot find module 'vue/dist/vue.esm.js'

### ISSUE THREAD

**Issue by hansonfang** [IndexXuan/vue-cli-plugin-vite#34]
vue.config.js内容为
```javascript
configureWebpack: {
externals: {
      'vue': 'Vue',
      'element-ui': 'ELEMENT',
      'echarts': 'echarts'
    },
    resolve: {
      extensions: ['.js', '.vue', '.json'],
      alias: {
        'vue$': 'vue/dist/vue.esm.js',
        '@': resolve('src')
      }
    }
}
```
html文件通过script引入vue，没有通过模块化安装
运行yarn vite命令报错如下：
```bash
error when starting dev server:
Error: Cannot find module 'vue/dist/vue.esm.js'
Require stack:
- D:\***\vip-operation-web-***\node_modules\vite-plugin-vue-cli\dist\index.js
- ...
```

**Comment by IndexXuan** [comment]
没有模块化安装 Vue 还配置了 vue/dist/esm几个意思啊 …

**Comment by IndexXuan** [comment]
我尝试下读取 externals 然后传递给 vite(rollup)来忽略报错

**Comment by IndexXuan** [comment]
After some research, I cannot support it.
maybe you need: https://www.npmjs.com/package/vite-plugin-cdn.

I don't think it is right to use CDN-style Vue in vite.
if you really want, you can use plugin above and pass-in to `vue-cli-plugin-vite` by `vue.config.js#pluginsOptions.vite.plugins`
