### ISSUE TITLE
MPA cannot run normally!

### ISSUE THREAD

**Issue by Jurool** [IndexXuan/vue-cli-plugin-vite#35]
SPA can start normally, but MPA is not.
I can't find any abnormalities, please help me, thank you.

Node: v12.22.1

[Demo](https://github.com/Jurool/vite-vue2-test) created by @vue/cli(4.5.13) here.

![image](https://user-images.githubusercontent.com/26647750/126278900-51702104-fee2-41bd-982a-48b87931fefb.png)

And the automatic open page link is `http://localhost:3000/undefined/index.html`.

The console has an error: 
![image](https://user-images.githubusercontent.com/26647750/126279381-fb26d670-e953-45fb-afd4-e3c8915ba79a.png)

**Comment by Jurool** [comment]
This is the network request panel:
![image](https://user-images.githubusercontent.com/26647750/126280455-9ec1af82-ba9a-4483-8976-1f03f62691c0.png)

**Comment by IndexXuan** [comment]
rename app to pages. it is vue-cli spec.

**Comment by Jurool** [comment]
> rename app to pages. it is vue-cli spec.

Are you talking about the folder name? I tried it and it still doesn't work.
![image](https://user-images.githubusercontent.com/26647750/126421648-b8c0232d-a361-4372-b320-8cb3d2d9b460.png)

**Comment by IndexXuan** [comment]
sorry too busy these days. the entry should be main.js/ts. yours is index.ts. I will clone your repro. also you can see the examples folder. It has MPA demo.

**Comment by Jurool** [comment]
> sorry too busy these days. the entry should be main.js/ts. yours is index.ts. I will clone your repro. also you can see the examples folder. It has MPA demo.

It works. The entry file should be main.ts. LOL

**Comment by IndexXuan** [comment]
@Jurool 
vue-cli SPA entry file must be main.{js,ts}, while MPA maybe can use others(but I am not support it right now). maybe somedays, not very hard.

**Comment by Jurool** [comment]
> @Jurool
> vue-cli SPA entry file must be main.{js,ts}, while MPA maybe can use others(but I am not support it right now). maybe somedays, not very hard.

Got it.
