### ISSUE TITLE
项目运行后控制台报错

### ISSUE THREAD

**Issue by TTcom** [IndexXuan/vue-cli-plugin-vite#37]
vue: @vue/cli 4.5.6
yarn:  1.22.5
node: v14.11.0
执行yarn vite后项目运行成功，但是随后会产生一个报错
![erro](https://user-images.githubusercontent.com/29853303/128354191-626e5ef6-d012-42ca-ac7f-f70b7d501fec.png)

**Comment by IndexXuan** [comment]
maybe vite-plugin-check issue. try disabledTypeChecker option.

https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/options.ts#L31

**Comment by TTcom** [comment]
> maybe vite-plugin-check issue. try disabledTypeChecker option.
> 
> https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/options.ts#L31



> maybe vite-plugin-check issue. try disabledTypeChecker option.
> 
> https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/options.ts#L31



> maybe vite-plugin-check issue. try disabledTypeChecker option.
> 
> https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/options.ts#L31



> maybe vite-plugin-check issue. try disabledTypeChecker option.
> 
> https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/options.ts#L31

Thank you

I closed it in vue.config.js

module.exports = {
    pluginOptions:{
        vite:{
            disabledTypeChecker:true
        }
    }
}
