### ISSUE TITLE
vite中的插件在配置文件vue.config.js中引入后不生效

### ISSUE THREAD

**Issue by TTcom** [IndexXuan/vue-cli-plugin-vite#38]
if you find some problems, please first read the  [FAQ](https://github.com/IndexXuan/vue-cli-plugin-vite/issues/9)

if you want some new feature, please know this plugin aims to let codebase work both in vite and vue-cli.
vue.config.js

const styleImport = require('vite-plugin-style-import');

module.exports = {
    pluginOptions:{
        vite:{
            disabledTypeChecker:true,
            plugins:[
                styleImport({
                    libs: [
                      {
                        libraryName: 'vant',
                        esModule: true,
                        resolveStyle: (name) => `vant/es/${name}/style`,
                      },
                    ],
                  })
            ]
        }
    }
}
pluginOptions 打印出来是空的

![1628237235(1)](https://user-images.githubusercontent.com/29853303/128478472-fd0f0574-443d-4305-b63d-d409b6372d94.png)

**Comment by IndexXuan** [comment]
可能有语法错误，加下 VITE_DEBUG=true 启动 yarn vite 试试

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/index.ts#L24

**Comment by TTcom** [comment]
> 可能有语法错误，加下 VITE_DEBUG=true 启动 yarn vite 试试

running: vite --config D:\autoproject\vite_vuecli\node_modules\vue-cli-plugin-vite\config\index.ts
TypeError: styleImport is not a function
提示不是一个函数
![1628239581(1)](https://user-images.githubusercontent.com/29853303/128483722-075998b6-cffc-427d-88ac-dcad7bff818d.png)
所以应该如果正确的引入vite插件呢？

**Comment by TTcom** [comment]
I solved it

add default

styleImport.default
