### ISSUE TITLE
提示 NO matching export in 'xxxx' fro import 'xxx'

### ISSUE THREAD

**Issue by yiyu-liao** [IndexXuan/vue-cli-plugin-vite#42]
![image](https://user-images.githubusercontent.com/43663210/130397642-660411d6-bc12-401b-81c4-ee50c06e6b4a.png)

如图，yarn run vite 预构建阶段出现的，请问有遇过这种情况嘛？

**Comment by IndexXuan** [comment]
这个就是所见即所得的报错，应该是代码对于 esm 的用法确实有问题，自己检查下。或者尝试 exclude 这个报错的依赖

**Comment by IndexXuan** [comment]
或者说更好的方式是尝试在 vite issue 中搜索，不是本插件导致的问题
