### ISSUE TITLE
suppport CommonJS module in node_modules

### ISSUE THREAD

**Issue by likeben** [IndexXuan/vue-cli-plugin-vite#43]

**Comment by IndexXuan** [comment]
?

**Comment by likeben** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/24544714/130455030-b9d5afb7-51fc-4668-8eac-85b89bcd6b77.png">

**Comment by IndexXuan** [comment]
you can try optimizeDeps.include for commonjs and this is vite issue, not this plugin. also no repro demo means I can do nothing to help.

**Comment by likeben** [comment]
Yeah, I found it's a vite bug
vitejs/vite#2346
