### ISSUE TITLE
how to config css less options

### ISSUE THREAD

**Issue by icepole-jon** [IndexXuan/vue-cli-plugin-vite#44]
I'm using a custom less var file to modify theme, this config work fine with vue-cli
```js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        lessOptions: {
          modifyVars: {
            hack: `true; @import "/src/assets/css/var.less";`,
          },
        },
      },
    },
  },
}
```
I add some vite config, but not work with this plugin
```js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        lessOptions: {
          modifyVars: {
            hack: `true; @import "/src/assets/css/var.less";`,
          },
        },
      },
    },
    preprocessorOptions: {
      less: {
        modifyVars: {
          blue: "#3875c6",
          hack: `true; @import "/src/assets/css/var.less";`,
        },
      },
    },
  },
}
```
am i miss something?

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L142

maybe due to my fault. would you mind test locally and send fixed PR of this handle line. thanks.

**Comment by icepole-jon** [comment]
> https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L142
> 
> maybe due to my fault. would you mind test locally and send fixed PR of this handle line. thanks.

看了下你这条源码。。是因为两种配置之间少了一层```lessOptions```
改成这样就行了
```js
module.exports = {
css: {
    loaderOptions: {
      less: {
        // lessOptions: {
        modifyVars: {
          hack: `true; @import "/src/assets/css/var.less";`,
        },
        // },
      },
    },
  },
}
```

这样用vite运行是没问题了，但是用vue-cli打包的时候就会报错了，毕竟少了一层。。
有什么办法兼容吗

**Comment by IndexXuan** [comment]
如果都是少同样的一层(scss/less)等，可以统一 transform 兼容，有空贡献个 PR 么老哥

**Comment by icepole-jon** [comment]
兄弟。。我来问问题，你居然想让我敲代码😂

```js
config.css = config.css || {}
css.loaderOptions && Object.entries(css.loaderOptions).forEach(([loader, options]) => {
  Object.assign(options, { ...options?.[`${loader}Options`] })
})
config.css.preprocessorOptions = css.loaderOptions
```

**Comment by IndexXuan** [comment]
哈～ 贡献开源啊，我要晚上或者明天才有空～

**Comment by IndexXuan** [comment]
https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders
@icepole-jon 看了下 vue-cli 官方说明，没说要加一层 lessOptions 啊

```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      // pass options to sass-loader
      // @/ is an alias to src/
      // so this assumes you have a file named `src/variables.sass`
      // Note: this option is named as "prependData" in sass-loader v8
      sass: {
        additionalData: `@import "~@/variables.sass"`
      },
      // by default the `sass` option will apply to both syntaxes
      // because `scss` syntax is also processed by sass-loader underlyingly
      // but when configuring the `prependData` option
      // `scss` syntax requires an semicolon at the end of a statement, while `sass` syntax requires none
      // in that case, we can target the `scss` syntax separately using the `scss` option
      scss: {
        additionalData: `@import "~@/variables.scss";`
      },
      // pass Less.js Options to less-loader
      less:{
        // http://lesscss.org/usage/#less-options-strict-units `Global Variables`
        // `primary` is global variables fields name
        globalVars: {
          primary: '#fff'
        }
      }
    }
  }
}
```

vue-cli 文档错了还是 ？

**Comment by IndexXuan** [comment]
@icepole-jon 没用过 less，scss 总之是不用加这一层的。我建议这样：
1. `package.json` 里 "vite" 命令改成 `"VITE=true node bin/vite"`，加一个当前是使用 `vite` 的环境变量
2. `vue.config.js` 里根据 process.env.VITE 是否开启，来设置给 vue-cli 还是给 vite 的 css.loaderOptions，类似于三目运算符返回 `VITE === true ? ${给 vite 的} : ${给 vue-cli}` 的

你看如何

**Comment by icepole-jon** [comment]
@IndexXuan 文档没提，但是编译的时候就会报错了，应该是用了loader
用了下其它loader的文档，也是有这一层的
scss是特例项
![](https://files.catbox.moe/d5hzst.png)
[https://github.com/webpack-contrib/sass-loader#options](https://github.com/webpack-contrib/sass-loader#options)
![](https://files.catbox.moe/b3sdga.png)

**Comment by IndexXuan** [comment]
我怀疑和 loader 版本也有关系，还是用我建议的在用户侧做选择吧，你看如何。
貌似 loader 6.x / 8.x / 10.x 都有细微变化，我写死在 `vite-plugin-vue-cli` 做转换貌似也不行

**Comment by icepole-jon** [comment]
我改用 additionalData 加载文件了😂
跳过了这个问题

**Comment by IndexXuan** [comment]
@icepole-jon 看了下，你的代码貌似可以，都 merge 到一层，可以冗余一些属性。我弄下发版你试试。稍等

**Comment by icepole-jon** [comment]
我试了下是没问题，可以把```...```省掉
```js
css.loaderOptions && Object.entries(css.loaderOptions).forEach(([loader, options]) => {
  Object.assign(options, options?.[`${loader}Options`])
})
```

**Comment by IndexXuan** [comment]
v1.4.4
