### ISSUE TITLE
resolve.extensions is invalid

### ISSUE THREAD

**Issue by GATING** [IndexXuan/vue-cli-plugin-vite#45]
```js
module.exports = {
  configureWebpack: {
          resolve: {
              extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.vue'],
              alias: {
                  '@': resolve('src'),
                  '@comp': resolve('src/components')
              }
          }
      }
}
```
怎么样才可以正确配置忽略的拓展名

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L131
never support infer `resolve.extensions` from `vue.config.js` for this plugin inner `vite.config.ts`

PR is Welcome(vite-plugin-vue-cli above) if you do need that.

**Comment by GATING** [comment]
> https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L131
> never support infer `resolve.extensions` from `vue.config.js` for this plugin inner `vite.config.ts`
> 
> PR is Welcome(vite-plugin-vue-cli above) if you do need that.

想问下有计划支持下吗?

**Comment by IndexXuan** [comment]
v1.4.6
