### ISSUE TITLE
Using fixed dependencies versions

### ISSUE THREAD

**Issue by Akryum** [IndexXuan/vue-cli-plugin-vite#46]
Why [`dependencies`](https://github.com/IndexXuan/vue-cli-plugin-vite/blob/f7097c219b0ca3979711474a2c1cfc601b6aaf62/package.json#L31-L46) is using fixed versions? We can't upgrade those packages in our project because of this.

**Comment by IndexXuan** [comment]
because anything about vite is inner handled and tested with these versions. e.g. if you want lower version vite-plugin-checker, it will not work. If you really want your version, use resolutions.
