### ISSUE TITLE
‘--host’ not working

### ISSUE THREAD

**Issue by czs0906** [IndexXuan/vue-cli-plugin-vite#47]
1. with '--config', '--host' not work
![issue](https://user-images.githubusercontent.com/68422863/132324859-88d6fb68-c2ca-4e8c-9aad-db6376601d79.png)

2. without '--config', '--host' work
![issue2](https://user-images.githubusercontent.com/68422863/132325324-c126d412-b109-480f-aa96-cee55c996c49.png)

**Comment by IndexXuan** [comment]
it is vite by design. If you want to config host, see here. https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L161 something like you can put DEV_HOST at .env.development.

**Comment by czs0906** [comment]
add `devServer: {
    host: '0.0.0.0'
  }` to `vue-config.js` can solve my problem
