### ISSUE TITLE
Incompatibility with unplugin-icons

### ISSUE THREAD

**Issue by Akryum** [IndexXuan/vue-cli-plugin-vite#49]
The default alias [`{ find: /^~/, replacement: '' }`](https://github.com/IndexXuan/vite-plugin-vue-cli/blob/c006b51ce399b297a8de14edc10d4cdcf34a32fa/src/index.ts#L128) removes the `~` in `~icons/...` paths breaking [unplugin-icons](https://github.com/antfu/unplugin-icons).

Example path: `~icons/feather/search`

**Comment by IndexXuan** [comment]
yes it is not css-loader syntax but weird… will hack handle it.

**Comment by Akryum** [comment]
Workaround vite plugin:

```js
{
  name: 'vite-fix-unplugin-icons',
  enforce: 'post',
  config (config) {
    // https://github.com/IndexXuan/vue-cli-plugin-vite/issues/49
    const index = config.resolve.alias.findIndex(a => a.find.toString() === '/^~/')
    if (index !== -1) config.resolve.alias.splice(index, 1)
  },
}
```

**Comment by IndexXuan** [comment]
really. just remove it will make some css-loader syntax compat failed.

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L128
I think we can change this regexp except for icons. can you try?

**Comment by Akryum** [comment]
https://regex101.com/r/TODWDz/1

**Comment by Akryum** [comment]
Maybe it could be configurable?

**Comment by IndexXuan** [comment]
your regexp works? I will try it tomorrow. If it works, I dont think it need configurable.

**Comment by IndexXuan** [comment]
@Akryum publish v1.4.9 by update inner `vite-plugin-vue-cli` for alias regexp you provided. It works for me.
https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/examples/my-spa-js-app/src/App.vue#L11
https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/examples/my-spa-js-app/vue.config.js#L8-L13

**Comment by IndexXuan** [comment]
aha, `unplugin` and `vue-cli-plugin-vite` plays well in nature, very nice ~

**Comment by IndexXuan** [comment]
examples use vue-cli(yarn build) will report error of sourcemap ... so I comment it ...
yarn vite:build is right.

I dont know. maybe `unplugin-icons` issue.
