### ISSUE TITLE
devServer里cookie的问题

### ISSUE THREAD

**Issue by jaysding** [IndexXuan/vue-cli-plugin-vite#50]
业务开发中接口需要本地种个cookie来模拟身份信息，但是用这个插件后的devServer里的cookie就不生效了，vue-cli是生效的

**Comment by IndexXuan** [comment]
提供的信息我不足够做任何事。
  我们是使用 devServer.before 来做的，不知道你们怎么做的。我也是尽可能兼容 devServer，但是 vite devServer 底层是 connect，webpack devServer 是 express。
