### ISSUE TITLE
`require.context` transform in lazy mode doesn't match Webpack behavior

### ISSUE THREAD

**Issue by henribru** [IndexXuan/vue-cli-plugin-vite#51]
When using `require.context` in lazy mode, the result of calling the context will be a promise that resolves to the module. That is, in `const context = require.context(..., ..., ..., 'lazy'); const foo = context('foo');`, `foo` will be a promise. That means if you want to use it as an async component you need to do `defineAsyncComponen(() => foo)`, because `defineAsyncComponent` expects a function that returns a promise. However, ` vue-cli-plugin-vite` is transforming this such that `foo` is actually a function that returns a promise, so the value passed to `defineAsyncComponent` will be a function returning a function returning a promise, which doesn't work. The culprit seems to be [here](https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/lib/resolve.ts#L34), I think the import should be returned directly instead of wrapped in an arrow function. I would be happy to create a PR for this if needed.

**Comment by IndexXuan** [comment]
PR is Welcome. thanks.

**Comment by IndexXuan** [comment]
v1.4.11
thanks for PR.
