### ISSUE TITLE
Upgrade vite and vue-plugin

### ISSUE THREAD

**Issue by henribru** [IndexXuan/vue-cli-plugin-vite#52]
There have been some great changes to vite and vue-plugin recently, e.g. performance improvements and Typescript support in templates. It would be awesome if the dependencies of this plugin were updated so we could take advantage of changes. I would make a PR myself except I'm not sure how tightly knit the plugin is with Vite internals, so I'm a bit worried about breaking something.

**Comment by IndexXuan** [comment]
I know vite 2.6 and new vite-plugin-vue. But I am on holiday. Also I am worried about vue-cli not support template ts and make dev feature only which is not the goal of this plugin.

**Comment by henribru** [comment]
You can actually use Typescript in templates with vue-cli now, you just add `enableTsInTemplate: true` to the `vue-loader` config (see https://github.com/vuejs/vue-loader/tree/next#v16-only-options).

No rush though, enjoy your holiday!

**Comment by IndexXuan** [comment]
thanks. you can use yarn resolutions or pnpm override to upgrade deps yourself. after test locally and PR is welcome.

**Comment by IndexXuan** [comment]
v1.5.0

**Comment by henribru** [comment]
Thank you!
