### ISSUE TITLE
您好 想请问一下关于多页 多入口的配置问题

### ISSUE THREAD

**Issue by jc840031139** [IndexXuan/vue-cli-plugin-vite#53]
在vue.config.js 配置了 入口信息
![image](https://user-images.githubusercontent.com/34274229/138702666-f0ec64a8-16f8-45e8-85f2-d75141642980.png)
启动 run vite 后 发现html文件默认入口文件为/src/main.js  这个是怎么配置呢

**Comment by IndexXuan** [comment]
目前应该是不支持非 src/pages 目录的多页 MPA
https://github.com/IndexXuan/vue-cli-plugin-vite/blob/main/config/index.ts#L90

这插件也是我写的，目前没法透穿参数给他，建议符合 vue-cli 标准目录结构，或者你PR 贡献下可以透穿参数给底层的 vite-plugin-mpa

https://github.com/IndexXuan/vite-plugin-mpa/blob/main/src/index.ts#L12

**Comment by jc840031139** [comment]
0.0  意思是可以使用 vite-plugin-map 来实现MPA项目吗  它也是支持vue-cli 创建的项目吗

**Comment by IndexXuan** [comment]
不是这意思，为了让 vue-cli 项目能使用 vite，我写了一堆 vite 插件来实现 vue-cli 功能。这个插件是底层，目前没开放参数来自定义，你如果想弄成 src/其他目录，需要 pr
