### ISSUE TITLE
feat: 样式全局导入

### ISSUE THREAD

**Issue by l246804** [IndexXuan/vue-cli-plugin-vite#54]
![image](https://user-images.githubusercontent.com/53589602/142181206-cbdec5cc-1b07-41ee-97ad-e57e6a4147bf.png)

这是我在 `vue.config.js` 中对全局样式混入的处理，请问在该插件中应该如何配置？查看源码时并为发现可添加 `vite css` 的功能。

期待添加可以 `vite css` 配置项。

**Comment by IndexXuan** [comment]
基于自定义 loader 做的事情，一般不好做，你可以看下如何在 vite 中开发等价的效果（例如你找到第三方 vite 插件或者自己开发），然后使用 plugins 引入这个 vite plugin.

**Comment by l246804** [comment]
![image](https://user-images.githubusercontent.com/53589602/142182681-38686dbc-3110-4130-9548-d30fa1b66a25.png)

vite 中有对 css 预处理器的配置项，我希望能够添加对该配置项的支持，就像 `plugins` 和 `optimizeDeps` 配置项一样，由使用者传入以达到预期的效果。

**Comment by IndexXuan** [comment]
这个配置项已经支持啊，你可以看下 bug 在哪？ 提 PR

**Comment by IndexXuan** [comment]
https://github.com/IndexXuan/vite-plugin-vue-cli/blob/main/src/index.ts#L155

**Comment by l246804** [comment]
![image](https://user-images.githubusercontent.com/53589602/142184458-040bbddb-c4a1-4c9b-ba1c-e8db4c357b07.png)

应该是因为注入全局资源用的是 `style-resource-loader` ，所以插件内部无法感知这些配置项导致的，所以是否需要在 REDEME.md 中注明或者额外增加预处理配置项呢？

**Comment by IndexXuan** [comment]
如果算上自定义 loader，我这个插件工作就做不完了，最多是 vue.config.js 里有的，我尽量做等价转为 vite。这个不适合 readme 特别注明某某 loader。

**Comment by l246804** [comment]
好的，感谢解答🙏插件用着挺方便的👍



---原始邮件---
发件人: "PENG ***@***.***&gt;
发送时间: 2021年11月17日(周三) 晚上6:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IndexXuan/vue-cli-plugin-vite] feat: 样式全局导入 (Issue #54)




 
如果算上自定义 loader，我这个插件工作就做不完了，最多是 vue.config.js 里有的，我尽量做等价转为 vite。这个不适合 readme 特别注明某某 loader。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
