### ISSUE TITLE
使用jsx时热更新无效

### ISSUE THREAD

**Issue by iamouyang21** [IndexXuan/vue-cli-plugin-vite#55]
if you find some problems, please first read the  [FAQ](https://github.com/IndexXuan/vue-cli-plugin-vite/issues/9)

if you want some new feature, please know this plugin aims to let codebase work both in vite and vue-cli.

使用jsx时热更新无效。demo代码：
<script lang="jsx">
  render() {
    return <div>1212</div>
  }
</script>

vite.config.js配置代码:

{
  // ...
  pluginOptions: {
    vite: {
      /**
       * Plugin[]
       * @default []
       */
      plugins: [vitecommonjs()]
      /**
       * Vite UserConfig.optimizeDeps options
       * recommended set `include` for speedup page-loaded time, e.g. include: ['vue', 'vue-router', '@scope/xxx']
       * @default {}
       */
      optimizeDeps: {},
      /**
       * type-checker, recommended disabled for large-scale old project.
       * @default false
       */
      disabledTypeChecker: true,
      /**
       * lint code by eslint
       * @default false
       */
      disabledLint: true,
      cssLoaderCompat: false,
     itePluginVue3Options: {
        jsx: true
     }
    }
  },
}

**Comment by IndexXuan** [comment]
信息太少，无可奈何
