### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'store' before initialization

### ISSUE THREAD

**Issue by rcoundon** [IndexXuan/vue-cli-plugin-vite#8]
I'm trying to get this working with an existing Vue 2 app but I'm getting the error:

Uncaught ReferenceError: Cannot access 'store' before initialization

I have a folder within:
```
src
  store
    index.js
    store.js
  main.js
```

main.js imports the store as such:

```
import store from './store/index.js';
```
and initialises the Vue instance like so:
```
export const app = new Vue({
  render: (h) => h(App),
  store,
  router,
  i18n,
}).$mount('#app');
```
index.js in the store folder looks like:
```
import Vue from 'vue';
import Vuex from 'vuex';
import { state, mutations, actions, getters } from './store.js';
import createPersistedState from 'vuex-persistedstate';

Vue.use(Vuex);

export default new Vuex.Store({
  state,
  mutations,
  actions,
  getters,
  plugins: [
    createPersistedState({
      storage: window.sessionStorage,
    }),
  ],
});

```

Am I doing something wrong?

**Comment by a20185** [comment]
@rcoundon can you share a minimum reproduction repo or link for this case?

**Comment by IndexXuan** [comment]
@rcoundon Vite Server start or not ? The error from chrome console or terminal ?
Give me the reproduction to help.

**Comment by rcoundon** [comment]
> @rcoundon can you share a minimum reproduction repo or link for this case?

Ok, I'll try to get this to you today.

**Comment by rcoundon** [comment]
> @rcoundon Vite Server start or not ? The error from chrome console or terminal ?
> Give me the reproduction to help.

Yes, vite server started, it is an error in the browser console and the web application doesn't render

**Comment by rcoundon** [comment]
It turns out this was due to a circular dependency. The store was importing the Vue app to reference i18n
